# Generated by Django 3.1.3 on 2022-12-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221216_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=1),
        ),
    ]
