# Generated by Django 3.1.3 on 2022-12-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20221218_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='password', max_length=16),
        ),
    ]
