# Generated by Django 3.1.3 on 2023-01-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20230103_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='balance_BTC',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance_USD',
            field=models.FloatField(default=0),
        ),
    ]
