# Generated by Django 3.1.3 on 2023-01-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230103_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='surname',
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance_BTC',
            field=models.FloatField(default=3),
        ),
    ]
