# Generated by Django 3.1.3 on 2023-01-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20230103_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance_BTC',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='want_to_buy',
            field=models.FloatField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='want_to_sell',
            field=models.FloatField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
