# Generated by Django 3.1.3 on 2023-01-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20230114_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance_BTC',
            field=models.FloatField(default=8),
        ),
    ]
