# Generated by Django 3.1.3 on 2023-01-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20230115_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance_BTC',
            field=models.FloatField(default=9),
        ),
    ]
