# Generated by Django 3.1.3 on 2023-01-15 23:22

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20230115_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance_BTC',
            field=models.FloatField(default=8),
        ),
    ]
