# Generated by Django 3.1.3 on 2023-01-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20230115_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initial_price',
            field=models.FloatField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='initial_want_to_buy',
            field=models.FloatField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='initial_want_to_sell',
            field=models.FloatField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance_BTC',
            field=models.FloatField(default=9),
        ),
    ]
