# Generated by Django 3.1.3 on 2023-01-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20230120_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='trend',
            new_name='trend_BTC',
        ),
        migrations.AddField(
            model_name='customer',
            name='trend_USD',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance_BTC',
            field=models.FloatField(default=10),
        ),
    ]
