# Generated by Django 3.1.3 on 2023-01-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20230123_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance_BTC',
            field=models.FloatField(default=2),
        ),
    ]
